### ISSUE TITLE
مشکل در استفاده از api

### ISSUE THREAD

**Issue by masoodbayati** [amerandish/farsava-samples-python#2]
همونطور که گفتین پسوند
wav
فرستادم و مدت زمانش هم ۴ ثانیه بود ولی ارور زیر رو میده
413 Client Error: Request Entity Too Large

**Comment by AminTaghikhani** [comment]
سلام وقت بخیر
دوست عزیز
به کدام سرور دارید درخواست میزنید؟
از کدام متد استفاده می کنید؟

**Comment by sanazmortazavi** [comment]
@AminTaghikhani 
سلام. من از سرویس متن های کوتاه شما وقتی استفاده میکنم برای یک ویس پونزده ثانیه ای خطا میده که زیادی بزرگه و قتی هم از سرویس متن های طولانی می خوام استفاده کنم این خطا رو میده:

 'uri' protocol is not supported

**Comment by AminTaghikhani** [comment]
سلام وقت بخیر

سرویس متن های طولانی در دسترس نیست در حال حاضر
فایلی که ارسال میکنید چه نوعی هست؟
اطلاعات فایل را اگر می شود ارسال کنید.
حجم فایل، نوع فایل، نرخ بیت، نرخ نمونه برداری

**Comment by sanazmortazavi** [comment]
@AminTaghikhani 
type : WAV
size: 6.82 MB
bitrate : 1536 Kbps
sample rate : 48KH
channel : 2ch

بعد طبیعیه که انقدر طول میکشه تا جواب بیاد؟

**Comment by AminTaghikhani** [comment]
@sanazmortazavi 
سلام مجدد
لطفا فایل را به صورت تک کانال ارسال کنید.
در صورتی که نیاز داشتید از دستور زیر می توانید استفاده کنید

`
ffmpeg -i yourFilePath -ac 1 -ar 16000 outputFile.wav
`

مدت زمان فایل چقدر هست؟ که بتوانم راهنمایی کنم

**Comment by sanazmortazavi** [comment]
@AminTaghikhani 
سلام من به صورت تک کانال هم میفرستم باز خطای 413 میده و 
request entity too large
فایل هم سی و هفت ثانیه است

**Comment by AminTaghikhani** [comment]
درصورتی که برای شما مقدور هست فایل را به ایمیل زیر ارسال کنید تا بتوانم بهتر راهنمایی کنم.
amin@amerandish.com

**Comment by sanazmortazavi** [comment]
@AminTaghikhani 
فرستادم خیلی ممنون از لطفتون.
